version: '3.7'

networks:
  cats:
    driver: bridge 

services:
  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: app_cats
    entrypoint: "/test-task-cats/docker/build.sh"
    ports:
      - 8000:8000
    networks:
      - cats
    depends_on:
      - redis
      - db
    links:
      - db
      - redis

  db:
    image: postgres
    container_name: db_cats
    ports:
      - 4545:5432
    env_file:
      - .env
    networks:
      - cats

  redis:
    image: redis
    container_name: redis_cats
    ports:
      - 5454:6379
    networks:
      - cats
    
  